---
# tasks file for common
- name: Change hostname
  become: true
  ansible.builtin.hostname:
    name: '{{ hostname }}'

- name: Install ZSh
  become: true
  ansible.builtin.package:
    name: zsh
    state: present
