---
# tasks file for common
- name: Change hostname
  become: true
  ansible.builtin.hostname:
    name: '{{ hostname }}'

- name: Create user
  become: true
  ansible.builtin.user:
      name: '{{ username }}'
      groups: sudo
      append: yes

- name: Create SSH Dir
  become: true
  become_user: '{{ username }}'
  ansible.builtin.file:
      path: ~/.ssh
      state: directory

- name: Copy SSH-Key
  become: true
  become_user: '{{ username }}'
  ansible.builtin.copy:
    src: .ssh/authorized_keys
    dest: ~/.ssh/authorized_keys
    owner: '{{ username }}'
    group: '{{ username }}'

- name: Install ZSh
  become: true
  ansible.builtin.package:
    name:
      - zsh
      - git
    state: latest

- name: Install OhMyZsh
  become: true
  become_user: '{{ username }}'
  git: repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh force=yes

- name: Get ZSh path
  ansible.builtin.shell: which zsh
  register: zsh_path

- name: Set ZSh as default shell
  become: true
  ansible.builtin.user:
      name: '{{ username }}'
      shell: '{{ zsh_path.stdout }}'
