---
- name: Create user
  become: true
  ansible.builtin.user:
      name: '{{ username }}'
      groups: sudo
      append: yes

- name: Create SSH Dir
  become: true
  become_user: '{{ username }}'
  ansible.builtin.file:
      path: ~/.ssh
      state: directory

- name: Copy SSH-Key
  become: true
  become_user: '{{ username }}'
  ansible.builtin.copy:
    src: .ssh/authorized_keys
    dest: ~/.ssh/authorized_keys
    owner: '{{ username }}'
    group: '{{ username }}'
