---
- name: Install ZSh
  become: true
  ansible.builtin.package:
    name:
      - zsh
      - git
      - curl
    state: latest

- name: Get ZSh path
  ansible.builtin.shell: which zsh
  register: zsh_path

- name: Set ZSh as default shell
  become: true
  ansible.builtin.user:
      name: '{{ user.login }}'
      shell: '{{ zsh_path.stdout }}'
