all:
  hosts:
    42Home:
      ansible_port: 4222
      ansible_host: 127.0.0.1
      student_login: thdelmas
  children:
    xubuntu:
        hosts:
          42OS:
            ansible_port: 4222
            ansible_host: 127.0.0.1
            student_login: thdelmas
            ansible_connection=ssh
            ansible_user=xubuntu
            ansible_ssh_pass=xubuntu
            
            
            centos / centos
Ubuntu  ubuntu / ubuntu
Debian  debian / debian
Fedora  fedora / fedora
Linux Mint  linuxmint / linuxmint
MX Linux  mxlinux / mxlinux
Manjaro  manjaro / manjaro
Elementary OS  elementaryos / elementaryos
Solus OS  solus / solus
Deepin  deepin / deepin
KDE neon  kdeneon / kdeneon
Antix  antix / antix
Kubuntu  kubuntu / kubuntu
Pop!_OS  popos / popos
openSUSE  opensuse / opensuse
EndeavourOS  endeavouros / endeavouros
Lubuntu  lubuntu / lubuntu
Arch Linux  archlinux / archlinux
Ubuntu Kylin  ubuntukylin / ubuntukylin
ArcoLinux  arcolinux / arcolinux
Kali Linux  kalilinux / kalilinux
Mageia  mageia / mageia
PCLinuxOS  pclinuxos / pclinuxos
Garuda Linux  garuda / garuda
Q4OS  q4os / q4os
Zorin OS  zorin / zorin
Xubuntu  xubuntu / xubuntu
AlmaLinux  almalinux / almalinux
Ubuntu MATE  ubuntumate / ubuntumate
Peppermint OS  peppermint / peppermint
Devuan  devuan / devuan
Endless OS  endless / endless
GeckoLinux  geckolinux / geckolinux
KaOS  kaos / kaos
Artix Linux  artix / artix
PureOS  pureos / pureos
Parrot OS  parrotos / parrotos
Feren OS  ferenos / ferenos
Ubuntu Studio  ubuntustudio / ubuntustudio
Rocky Linux  rockylinux / rockylinux

